%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Volumes/LEADE1/Paper_Code/WM989_noDrug_20150618_Summary.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 14-Feb-2019 13:26:20

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = "Sheet7";
opts.DataRange = "B3:O3";

% Specify column names and types
opts.VariableNames = ["EGFR", "WNT5A", "PDGFRB", "PDGFC", "SERPINE1", "NGFR", "NRG1", "FOSL1", "VEGFC", "AXL", "LOXL2", "RUNX2", "FGFR1", "JUN"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
WM989noDrug20150618Summary = readtable("/Volumes/MELANOMAII/Data/ParSetsAnalysis.xlsx", opts, "UseExcel", false);

%% Convert to output type
WM989noDrug20150618Summary = table2array(WM989noDrug20150618Summary);

%% Clear temporary variables
clear  opts