%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Volumes/LEADE1/data_and_figs/data_for_plots.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 02-May-2019 18:30:21

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = "Thres";
opts.DataRange = "A7:J22";

% Specify column names and types
opts.VariableNames = ["EdgeWeightThreshold", "NoDrug1", "NoDrug2", "Fourweeks1_Cluster1", "Fourweeks1_Cluster2", "Fourweeks1_Cluster3", "Foruweeks1_Cluster4", "Fourweeks2_Cluster1", "Fourweeks2_Cluster2", "Fourweeks2_Cluster3"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
dataforplots = readtable("/Volumes/MELANOMAII/Data/PhixerData.xlsx", opts, "UseExcel", false);

%% Convert to output type
dataforplots = table2array(dataforplots);

%% Clear temporary variables
clear  opts